apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup
      image: alpine
      script: |
        #!/bin/sh
        echo "Cleaning up resources..."
        # Add cleanup commands here
        echo "Cleanup completed"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test
spec:
  steps:
    - name: test
      image: python:3.9
      script: |
        #!/usr/bin/env python3
        pip install -r requirements.txt
        pytest --testdox 